version: "3.1"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: qrx
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: smart_house
    networks:
      - default
networks:
  default:
    driver: bridge
